// examples/vue/src/main.tsx
/** @jsxImportSource vue */
import { computed, createApp, defineComponent, nextTick, ref } from 'vue'
import { useVirtualList } from '../../../src/vue'
import type { VueVirtualItem } from '../../../src/vue'
import {
  estimateMessageSize,
  estimateHorizontalMessageSize,
  getScenarioCode,
  getHorizontalMessageSizeClass,
  makeMessages,
  makeRandomMessage,
  pageSize,
  scenarioConfigs,
  totalMessageCount,
} from '../../shared/demo-data'
import type { ChatMessage, Scenario } from '../../shared/demo-data'
import './styles.css'

const iconUrl = new URL('../../../icon.png', import.meta.url).href

const PreText = defineComponent({
  name: 'PreText',
  props: {
    value: {
      type: String,
      required: true,
    },
  },
  setup(props) {
    return () => <pre class="pretext">{props.value}</pre>
  },
})

const MessageRow = defineComponent({
  name: 'MessageRow',
  props: {
    axis: {
      type: String as () => 'horizontal' | 'vertical',
      required: true,
    },
    isFirst: {
      type: Boolean,
      required: true,
    },
    isLast: {
      type: Boolean,
      required: true,
    },
    virtualItem: {
      type: Object as () => VueVirtualItem<ChatMessage>,
      required: true,
    },
    measureElement: {
      type: Function,
      required: true,
    },
  },
  setup(props) {
    return () => {
      const virtualItem = props.virtualItem
      const image = virtualItem.item.image

      return (
        <article
          ref={(element) =>
            props.measureElement(virtualItem.index, element, virtualItem.key)
          }
          class={[
            'message',
            props.axis === 'horizontal' ? 'horizontal-message' : '',
            props.axis === 'horizontal'
              ? getHorizontalMessageSizeClass(virtualItem.item)
              : '',
            props.isFirst ? 'edge-start' : '',
            props.isLast ? 'edge-end' : '',
            virtualItem.item.mine ? 'mine' : '',
          ]}
          style={virtualItem.style}
        >
          <div class="bubble">
            <div class="message-meta">
              <strong>{virtualItem.item.author}</strong>
              <span>#{virtualItem.item.id}</span>
            </div>
            <p>{virtualItem.item.text}</p>
            {image ? (
              <img
                alt={image.alt}
                class="message-image"
                loading="lazy"
                src={image.src}
              />
            ) : null}
            {virtualItem.item.preText ? (
              <PreText value={virtualItem.item.preText} />
            ) : null}
          </div>
        </article>
      )
    }
  },
})

const ChatListScenario = defineComponent({
  name: 'ChatListScenario',
  props: {
    scenario: {
      type: String as () => Scenario,
      required: true,
    },
  },
  setup(props) {
    const config = computed(() => scenarioConfigs[props.scenario])
    const loadedStart = ref(config.value.initialStart)
    const loadedEnd = ref(config.value.initialEnd)
    const insertedMessages = ref<ChatMessage[]>([])
    const loadingOlder = ref(false)
    const loadingNewer = ref(false)
    const showCode = ref(false)
    const insertSeed = ref(1)
    const didCenterInitialPosition = ref(false)
    const baseMessages = computed(() =>
      makeMessages(loadedStart.value, loadedEnd.value),
    )
    const messages = computed(() => {
      if (insertedMessages.value.length === 0) {
        return baseMessages.value
      }

      const nextMessages = [...baseMessages.value]
      for (const [index, message] of insertedMessages.value.entries()) {
        const insertAt = Math.min(
          nextMessages.length,
          Math.floor(
            ((index + 1) * nextMessages.length) /
              (insertedMessages.value.length + 1),
          ),
        )
        nextMessages.splice(insertAt, 0, message)
      }
      return nextMessages
    })
    const canLoadOlder = computed(
      () =>
        loadedStart.value > 0 &&
        (props.scenario === 'vertical-prepend' ||
          props.scenario === 'horizontal-prepend'),
    )
    const canLoadNewer = computed(
      () =>
        loadedEnd.value < totalMessageCount &&
        (props.scenario === 'vertical-append' ||
          props.scenario === 'horizontal-append'),
    )

    const loadOlder = () => {
      if (!canLoadOlder.value || loadingOlder.value) {
        return
      }

      loadingOlder.value = true
      window.setTimeout(() => {
        loadedStart.value = Math.max(0, loadedStart.value - pageSize)
        loadingOlder.value = false
      }, 420)
    }

    const loadNewer = () => {
      if (!canLoadNewer.value || loadingNewer.value) {
        return
      }

      loadingNewer.value = true
      window.setTimeout(() => {
        loadedEnd.value = Math.min(
          totalMessageCount,
          loadedEnd.value + pageSize,
        )
        loadingNewer.value = false
      }, 420)
    }

    const insertRandomMessage = () => {
      insertedMessages.value = [
        ...insertedMessages.value,
        makeRandomMessage(insertSeed.value),
      ]
      insertSeed.value += 1
    }

    const list = useVirtualList({
      items: messages,
      estimateSize:
        config.value.axis === 'horizontal'
          ? estimateHorizontalMessageSize
          : estimateMessageSize,
      getItemKey: (message) => message.id,
      gap: 10,
      horizontal: computed(() => config.value.axis === 'horizontal'),
      initialScrollToBottom: computed(
        () => config.value.initialPosition === 'bottom',
      ),
      onReachEnd: computed(() => (canLoadNewer.value ? loadNewer : undefined)),
      onReachStart: computed(() =>
        canLoadOlder.value ? loadOlder : undefined,
      ),
      preserveScrollPosition: true,
      edgeThreshold: 120,
      stickToBottom: computed(
        () =>
          props.scenario === 'vertical-prepend' ||
          props.scenario === 'horizontal-prepend',
      ),
    })
    const scrollToStartPoint = () => {
      if (config.value.initialPosition === 'bottom') {
        list.scrollToBottom()
        return
      }

      if (config.value.initialPosition === 'center') {
        list.scrollToIndex(Math.floor(messages.value.length / 2), 'center')
        return
      }

      list.scrollToOffset(0)
    }
    const rangeText = computed(
      () => `${list.range.value.startIndex}-${list.range.value.endIndex}`,
    )

    nextTick(() => {
      if (
        config.value.initialPosition !== 'center' ||
        didCenterInitialPosition.value
      ) {
        return
      }

      didCenterInitialPosition.value = true
      window.requestAnimationFrame(() => {
        list.scrollToIndex(Math.floor(messages.value.length / 2), 'center')
      })
    })

    return () => (
      <section class="scenario-panel">
        <div class="scenario-toolbar">
          <div>
            <strong>{config.value.title}</strong>
            <span>
              已加载 {messages.value.length} / {totalMessageCount} 条，源范围{' '}
              {loadedStart.value + 1}-{loadedEnd.value}，渲染范围{' '}
              {rangeText.value}
            </span>
          </div>
          <div class="actions">
            <button
              disabled={!canLoadOlder.value || loadingOlder.value}
              onClick={loadOlder}
              type="button"
            >
              {loadingOlder.value ? '加载中' : config.value.loadStartLabel}
            </button>
            <button
              disabled={!canLoadNewer.value || loadingNewer.value}
              onClick={loadNewer}
              type="button"
            >
              {loadingNewer.value ? '加载中' : config.value.loadEndLabel}
            </button>
            <button onClick={insertRandomMessage} type="button">
              随机插入
            </button>
            <button onClick={scrollToStartPoint} type="button">
              回到起点
            </button>
          </div>
        </div>

        <section
          ref={list.containerRef}
          class={[
            'viewport',
            'chat-viewport',
            config.value.axis === 'horizontal' ? 'horizontal-viewport' : '',
          ]}
          aria-label={`${config.value.title} virtual list`}
        >
          <div style={list.innerStyle.value}>
            {list.virtualItems.value.map((virtualItem) => (
              <MessageRow
                axis={config.value.axis}
                isFirst={virtualItem.index === 0}
                isLast={virtualItem.index === messages.value.length - 1}
                key={virtualItem.key}
                measureElement={list.measureElement}
                virtualItem={virtualItem}
              />
            ))}
          </div>
        </section>

        <div class="scenario-footer">
          <button
            class="code-toggle"
            onClick={() => (showCode.value = !showCode.value)}
            type="button"
          >
            {showCode.value ? '隐藏代码' : '显示代码'}
          </button>
        </div>

        {showCode.value ? (
          <pre class="code-panel code-panel-enter">
            <code>{getScenarioCode('Vue', props.scenario)}</code>
          </pre>
        ) : null}
      </section>
    )
  },
})

const App = defineComponent({
  name: 'VueChatDemo',
  setup() {
    return () => (
      <main class="app-shell">
        <header class="toolbar">
          <div class="brand">
            <img src={iconUrl} alt="" aria-hidden="true" />
            <div>
              <h1>Vue 聊天虚拟列表</h1>
              <p>四种列表从上到下同时展示，分别验证纵向和横向的双端加载。</p>
            </div>
          </div>
        </header>

        <section class="scenario-stack">
          {(Object.keys(scenarioConfigs) as Scenario[]).map((scenario) => (
            <ChatListScenario key={scenario} scenario={scenario} />
          ))}
        </section>
      </main>
    )
  },
})

createApp(App).mount('#app')

// examples/react/src/main.tsx
import { useCallback, useLayoutEffect, useMemo, useRef, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { useVirtualList } from '../../../src/react'
import type { ReactVirtualItem } from '../../../src/react'
import {
  estimateMessageSize,
  estimateHorizontalMessageSize,
  getScenarioCode,
  getHorizontalMessageSizeClass,
  makeMessages,
  makeRandomMessage,
  pageSize,
  scenarioConfigs,
  totalMessageCount,
} from '../../shared/demo-data'
import type { ChatMessage, Scenario } from '../../shared/demo-data'
import './styles.css'

const iconUrl = new URL('../../../icon.png', import.meta.url).href

function App() {
  return (
    <main className="app-shell">
      <header className="toolbar">
        <div className="brand">
          <img src={iconUrl} alt="" aria-hidden="true" />
          <div>
            <h1>React 聊天虚拟列表</h1>
            <p>四种列表从上到下同时展示，分别验证纵向和横向的双端加载。</p>
          </div>
        </div>
      </header>

      <section className="scenario-stack">
        {(Object.keys(scenarioConfigs) as Scenario[]).map((scenario) => (
          <ChatListScenario key={scenario} scenario={scenario} />
        ))}
      </section>
    </main>
  )
}

function ChatListScenario({ scenario }: { scenario: Scenario }) {
  const config = scenarioConfigs[scenario]
  const [loadedStart, setLoadedStart] = useState(config.initialStart)
  const [loadedEnd, setLoadedEnd] = useState(config.initialEnd)
  const [insertedMessages, setInsertedMessages] = useState<ChatMessage[]>([])
  const [loadingOlder, setLoadingOlder] = useState(false)
  const [loadingNewer, setLoadingNewer] = useState(false)
  const [showCode, setShowCode] = useState(false)
  const [insertSeed, setInsertSeed] = useState(1)
  const didCenterInitialPositionRef = useRef(false)
  const baseMessages = useMemo(
    () => makeMessages(loadedStart, loadedEnd),
    [loadedEnd, loadedStart],
  )
  const messages = useMemo(() => {
    if (insertedMessages.length === 0) {
      return baseMessages
    }

    const nextMessages = [...baseMessages]
    for (const [index, message] of insertedMessages.entries()) {
      const insertAt = Math.min(
        nextMessages.length,
        Math.floor(((index + 1) * nextMessages.length) / (insertedMessages.length + 1)),
      )
      nextMessages.splice(insertAt, 0, message)
    }
    return nextMessages
  }, [baseMessages, insertedMessages])

  const canLoadOlder =
    loadedStart > 0 &&
    (scenario === 'vertical-prepend' || scenario === 'horizontal-prepend')
  const canLoadNewer =
    loadedEnd < totalMessageCount &&
    (scenario === 'vertical-append' || scenario === 'horizontal-append')

  const loadOlder = useCallback(() => {
    if (!canLoadOlder || loadingOlder) {
      return
    }

    setLoadingOlder(true)
    window.setTimeout(() => {
      setLoadedStart((current) => Math.max(0, current - pageSize))
      setLoadingOlder(false)
    }, 420)
  }, [canLoadOlder, loadingOlder])

  const loadNewer = useCallback(() => {
    if (!canLoadNewer || loadingNewer) {
      return
    }

    setLoadingNewer(true)
    window.setTimeout(() => {
      setLoadedEnd((current) =>
        Math.min(totalMessageCount, current + pageSize),
      )
      setLoadingNewer(false)
    }, 420)
  }, [canLoadNewer, loadingNewer])

  const insertRandomMessage = useCallback(() => {
    setInsertedMessages((current) => [
      ...current,
      makeRandomMessage(insertSeed),
    ])
    setInsertSeed((current) => current + 1)
  }, [insertSeed])

  const list = useVirtualList({
    items: messages,
    estimateSize:
      config.axis === 'horizontal'
        ? estimateHorizontalMessageSize
        : estimateMessageSize,
    getItemKey: (message) => message.id,
    gap: 10,
    horizontal: config.axis === 'horizontal',
    initialScrollToBottom: config.initialPosition === 'bottom',
    onReachEnd: canLoadNewer ? loadNewer : undefined,
    onReachStart: canLoadOlder ? loadOlder : undefined,
    preserveScrollPosition: true,
    edgeThreshold: 120,
    stickToBottom:
      scenario === 'vertical-prepend' || scenario === 'horizontal-prepend',
  })

  const scrollToStartPoint = useCallback(() => {
    if (config.initialPosition === 'bottom') {
      list.scrollToBottom()
      return
    }

    if (config.initialPosition === 'center') {
      list.scrollToIndex(Math.floor(messages.length / 2), 'center')
      return
    }

    list.scrollToOffset(0)
  }, [config.initialPosition, list, messages.length])

  useLayoutEffect(() => {
    if (
      config.initialPosition !== 'center' ||
      didCenterInitialPositionRef.current ||
      list.range.startIndex === -1
    ) {
      return
    }

    didCenterInitialPositionRef.current = true
    window.requestAnimationFrame(() => {
      list.scrollToIndex(Math.floor(messages.length / 2), 'center')
    })
  }, [config.initialPosition, list, messages.length])

  return (
    <section className="scenario-panel">
      <div className="scenario-toolbar">
        <div>
          <strong>{config.title}</strong>
          <span>
            已加载 {messages.length} / {totalMessageCount} 条，源范围{' '}
            {loadedStart + 1}-{loadedEnd}，渲染范围 {list.range.startIndex}-
            {list.range.endIndex}
          </span>
        </div>
        <div className="actions">
          <button
            disabled={!canLoadOlder || loadingOlder}
            onClick={loadOlder}
            type="button"
          >
            {loadingOlder ? '加载中' : config.loadStartLabel}
          </button>
          <button
            disabled={!canLoadNewer || loadingNewer}
            onClick={loadNewer}
            type="button"
          >
            {loadingNewer ? '加载中' : config.loadEndLabel}
          </button>
          <button onClick={insertRandomMessage} type="button">
            随机插入
          </button>
          <button onClick={scrollToStartPoint} type="button">
            回到起点
          </button>
        </div>
      </div>

      <section
        ref={list.containerRef}
        className={`viewport chat-viewport ${
          config.axis === 'horizontal' ? 'horizontal-viewport' : ''
        }`}
        aria-label={`${config.title} virtual list`}
      >
        <div style={list.innerStyle}>
          {list.virtualItems.map((virtualItem) => (
            <MessageRow
              axis={config.axis}
              isFirst={virtualItem.index === 0}
              isLast={virtualItem.index === messages.length - 1}
              key={virtualItem.key}
              virtualItem={virtualItem}
            />
          ))}
        </div>
      </section>

      <div className="scenario-footer">
        <button
          className="code-toggle"
          onClick={() => setShowCode((current) => !current)}
          type="button"
        >
          {showCode ? '隐藏代码' : '显示代码'}
        </button>
      </div>

      {showCode ? (
        <pre className="code-panel code-panel-enter">
          <code>{getScenarioCode('React', scenario)}</code>
        </pre>
      ) : null}
    </section>
  )
}

function MessageRow({
  axis,
  isFirst,
  isLast,
  virtualItem,
}: {
  axis: 'horizontal' | 'vertical'
  isFirst: boolean
  isLast: boolean
  virtualItem: ReactVirtualItem<ChatMessage>
}) {
  const edgeClass =
    `${isFirst ? 'edge-start' : ''} ${isLast ? 'edge-end' : ''}`
  const horizontalSizeClass =
    axis === 'horizontal'
      ? getHorizontalMessageSizeClass(virtualItem.item)
      : ''

  return (
    <article
      ref={virtualItem.measureRef}
      className={`message ${axis === 'horizontal' ? 'horizontal-message' : ''} ${horizontalSizeClass} ${edgeClass} ${
        virtualItem.item.mine ? 'mine' : ''
      }`}
      style={virtualItem.style}
    >
      <div className="bubble">
        <div className="message-meta">
          <strong>{virtualItem.item.author}</strong>
          <span>#{virtualItem.item.id}</span>
        </div>
        <p>{virtualItem.item.text}</p>
        {virtualItem.item.image ? (
          <img
            alt={virtualItem.item.image.alt}
            className="message-image"
            loading="lazy"
            src={virtualItem.item.image.src}
          />
        ) : null}
        {virtualItem.item.preText ? (
          <PreText value={virtualItem.item.preText} />
        ) : null}
      </div>
    </article>
  )
}

function PreText({ value }: { value: string }) {
  return <pre className="pretext">{value}</pre>
}

createRoot(document.getElementById('root') as HTMLElement).render(<App />)
